# -*- coding: utf-8 -*-
"""Run the pediatric MPP evidence-graph RAG demo."""

from __future__ import annotations

import json
import os

from graph_rag_core import load_default_graph, render_evidence_answer
from graph_rag_core import build_evidence_payload
from MycoplasmaPneumonia.llm_client import get_llm_client


DEFAULT_QUESTION = "重症支原体肺炎（SMPP）儿童是否应常规使用糖皮质激素？"


def run_demo(
    question: str | None = None,
    output_file: str | None = None,
    use_llm: bool | None = None,
) -> str:
    base_dir = os.path.dirname(os.path.abspath(__file__))
    graph = load_default_graph(base_dir)
    clinical_question = question or DEFAULT_QUESTION
    llm_final_answer = _generate_llm_final_answer(clinical_question, graph, use_llm)
    markdown = render_evidence_answer(clinical_question, graph, llm_final_answer)

    if output_file is None:
        output_file = os.path.join(base_dir, "steroid_smpp_answer.md")

    with open(output_file, "w", encoding="utf-8") as file:
        file.write(markdown)

    return markdown


def _generate_llm_final_answer(question: str, graph, use_llm: bool | None) -> dict | None:
    llm = get_llm_client()
    if use_llm is False or not llm.enabled:
        return None

    system_prompt = (
        "You are generating the final answer section for a pediatric evidence-based "
        "clinical decision-support Graph RAG demo. Use only the provided evidence graph. "
        "Do not invent citations. Keep the answer in Chinese. Return only valid JSON "
        "with key final_answer_markdown."
    )
    payload = build_evidence_payload(question, graph)
    payload["output_constraints"] = [
        "Answer whether SMPP children should routinely use glucocorticoids.",
        "State that low-dose methylprednisolone is preferred over routine high-dose therapy.",
        "Mention safety risks and clinician review.",
        "Do not include a separate reasoning-process section; that is generated by code.",
    ]

    try:
        generated = llm.chat_json(system_prompt, payload)
    except Exception as exc:
        return {"llm_error": str(exc), "model": llm.config.model}

    answer = str(generated.get("final_answer_markdown", "")).strip()
    if not answer:
        return None
    return {"final_answer_markdown": answer, "model": llm.config.model}


def main() -> None:
    output_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "steroid_smpp_answer.md")
    markdown = run_demo(output_file=output_file)
    result = {
        "output_file": output_file,
        "characters": len(markdown),
        "status": "ok",
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
